ADD: recyclerView,ListAdapter with Flow,LiveData
DevCamp2Flame/FlameTalk_Android pull request #4
Opened 2022-01-09 10:03 UTC by 014967

온전히 Flow만 사용하는 것은 잘모르겠어서 LiveData와 함께 사용해서 더미데이터로 테스트를 해보았습니다
더미데이터 클래스는 나중에 db 보면서 바꿀려고 합니당

2022-01-09 10:55 UTC, paksuua commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/btn_view"
btn은 <Button>에서 쓰는 약어입니다. BottomNavigationView는 btnv로 써주세요

2022-01-09 10:55 UTC, paksuua commented on app/src/main/res/layout/item_chatting_room_list_two.xml
> +            android:text="ㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇ"
UI 테스트용 데이터는 
android:text=""에 넣으면 안됩니다.
tools:text=""에 넣으면 xml preview로 확인 가능하고 실질적으로 실행했을때 더미데이터를 넣고 싶으시면 데이터클래스에서 더미데이터를 만드는게 더 좋습니다.

2022-01-09 10:58 UTC, paksuua commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/btn_view"
btn은 Button의 타입 이름입니다.
btnv에서 왜 변경하셨는지 모르겠습니다.

2022-01-09 11:03 UTC, paksuua commented on app/src/main/java/com/sgs/devcamp2/flametalk_android/ui/MainActivity.kt
> +                binding.btnView.visibility = View.GONE
BottomNaviagationView 타입 약자 btn 쓰시면 안됩니다. btnv로 해주세요.

2022-01-09 11:03 UTC, paksuua commented on app/src/main/java/com/sgs/devcamp2/flametalk_android/ui/chatlist/ChatListAdapter.kt
> +// 클래스에서만 한번만 쓸려고하는 것
클래스의 역할을 이해할 수 있도록 주석 작성 부탁드립니다.

2022-01-09 11:04 UTC, paksuua requested changes
첫 풀리퀘 축하드려요! 남긴 코멘트 한번씩 확인 후 수정해주세요

2022-01-10 00:29 UTC, 014967 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/btn_view"
이런 오타인줄 알았네요

2022-01-10 00:33 UTC, 014967 commented on app/src/main/res/layout/item_chatting_room_list_two.xml
> +            android:text="ㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇ"
확인했습니다

2022-01-11 00:38 UTC, paksuua approved these changes
확인했습니다!

2022-01-11 00:39 UTC, merged